# Generated by Django 2.0.6 on 2018-06-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.Empleador'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_ini',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='insumo',
            field=models.ManyToManyField(help_text='Seleccione insumos', to='rooms.Insumo'),
        ),
        migrations.AddField(
            model_name='sala',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sala',
            name='estado',
            field=models.CharField(blank=True, choices=[('d', 'Disponible'), ('n', 'No disponible'), ('r', 'Reservada'), ('c', 'Confirmada')], default='p', help_text='Disponibilidad de la sala', max_length=1),
        ),
        migrations.AddField(
            model_name='sala',
            name='hora_disp_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='hora_disp_ini',
            field=models.TimeField(null=True),
        ),
    ]
