# Generated by Django 2.0.6 on 2018-06-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20180619_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['nombre']},
        ),
    ]
